spring.application.name=ventro_testing

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/ventro_test
spring.datasource.username=postgres
spring.datasource.password=112233

# JWT
jwt.secret=FVPr6Q/fVlHGZkElZubC0Zaxv657dPUfDQ4o9DADjSin7+uST1d2A5klMWrMK8fmSl3doyf2wn5zj56VC+qqCg==

# MyBatis
mybatis.type-handlers-package=com.ventro.ventro_testing.utils

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=somveasna00@gmail.com
spring.mail.password=rgygiajnpvuplknk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs